version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/frontend/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "orchflow-team"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical deps
      - dependency-name: "tauri"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-major"]

  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "orchflow-team"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major updates for frameworks
      - dependency-name: "@tauri-apps/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "svelte"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"