# Pre-commit hooks for Orchflow Desktop
# See https://pre-commit.com for more information
repos:
  # TypeScript and JavaScript linting
  - repo: local
    hooks:
      # TypeScript type checking - CRITICAL
      - id: typescript-check
        name: TypeScript Check
        entry: npm run check
        language: system
        files: \.(ts|tsx|svelte)$
        pass_filenames: false
        
      # ESLint - fix auto-fixable issues, fail on errors
      - id: eslint-fix
        name: ESLint Fix & Check
        entry: npm run lint:fix
        language: system
        files: \.(ts|tsx|js|jsx|svelte)$
        pass_filenames: false
        
      # Rust compilation check - CRITICAL
      - id: rust-check
        name: Rust Compilation Check
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false
        
      # Rust formatting
      - id: rust-fmt
        name: Rust Format
        entry: cargo fmt --all -- --check
        language: system
        files: \.rs$
        pass_filenames: false
        
      # Rust clippy lints - warnings only
      - id: rust-clippy
        name: Rust Clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false

  # Code formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Basic file checks
      - id: trailing-whitespace
        exclude: \.(md|diff)$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
      - id: check-json
        exclude: tsconfig\.json$ # Allow comments in tsconfig
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      
      # Security checks
      - id: detect-private-key
      - id: check-executables-have-shebangs

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(ts|tsx|js|jsx|json|yaml|yml|md)$
        exclude: |
          (?x)^(
            package-lock\.json|
            \.svelte-kit/.*|
            node_modules/.*|
            dist/.*|
            build/.*
          )$

  # Svelte formatting
  - repo: local
    hooks:
      - id: svelte-format
        name: Svelte Format Check
        entry: npx prettier --check
        language: system
        files: \.svelte$
        args: ['--plugin', 'prettier-plugin-svelte']

  # Security and quality checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock$|
            \.git/.*|
            node_modules/.*|
            target/.*
          )$

# Configuration
default_stages: [commit]
fail_fast: false # Run all hooks even if some fail
minimum_pre_commit_version: "3.0.0"